AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']